"""empty message

Revision ID: 31a2963a2757
Revises: 
Create Date: 2021-05-07 03:41:06.195645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31a2963a2757'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('apellidos', sa.String(length=80), nullable=False),
    sa.Column('nacimiento', sa.String(length=80), nullable=True),
    sa.Column('sexo', sa.String(length=80), nullable=False),
    sa.Column('telefono', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('ordenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=120), nullable=True),
    sa.Column('monto', sa.String(length=80), nullable=False),
    sa.Column('productos', sa.String(length=250), nullable=False),
    sa.Column('dirección', sa.String(length=250), nullable=False),
    sa.Column('metodo', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['usuario'], ['user.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('catego_prod', sa.String(length=80), nullable=True),
    sa.Column('precio', sa.String(length=80), nullable=False),
    sa.Column('detalles', sa.String(length=250), nullable=False),
    sa.Column('imagen', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['catego_prod'], ['categoria.nombre'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('productos')
    op.drop_table('ordenes')
    op.drop_table('user')
    op.drop_table('pago')
    op.drop_table('categoria')
    # ### end Alembic commands ###
