"""empty message

Revision ID: b34db751cca0
Revises: 40b74942324b
Create Date: 2021-04-20 15:05:12.802011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b34db751cca0'
down_revision = '40b74942324b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.add_column('productos', sa.Column('catego_prod', sa.String(length=80), nullable=True))
    op.create_foreign_key(None, 'productos', 'categoria', ['catego_prod'], ['nombre'])
    op.drop_column('productos', 'categoria')
    op.add_column('user', sa.Column('direccion', sa.String(length=250), nullable=False))
    op.add_column('user', sa.Column('metodo_pago', sa.String(length=80), nullable=True))
    op.add_column('user', sa.Column('nombre', sa.String(length=80), nullable=False))
    op.add_column('user', sa.Column('telefono', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'user', 'pago', ['metodo_pago'], ['nombre'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'telefono')
    op.drop_column('user', 'nombre')
    op.drop_column('user', 'metodo_pago')
    op.drop_column('user', 'direccion')
    op.add_column('productos', sa.Column('categoria', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'productos', type_='foreignkey')
    op.drop_column('productos', 'catego_prod')
    op.drop_table('pago')
    op.drop_table('categoria')
    # ### end Alembic commands ###
